version: '3'
services:

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD
      - POSTGRES_DB=${DATABASE_NAME}

    volumes:
      - postgres-db:/var/lib/postgresql/data
    ports:
      - "5433:5432"

    healthcheck:
         test: ["CMD-SHELL", "pg_isready -U postgres"]
         interval: 10s
         timeout: 5s
         retries: 5

  api:
      image: ayushthakkur1701/fastapi

      # volumes:
      # - type: bind
      #   source: .
      #   target: /usr/src/app
      # working_dir: /usr/src/app

      depends_on:
        postgres:
          condition: service_healthy

      ports: 
          - 80:8000

      environment:
        -  DATABASE_HOSTNAME=${DATABASE_HOSTNAME} #name of postgres service
        -  DATABASE_PORT=${DATABASE_PORT}
        -  DATABASE_USERNAME=$DATABASE_USERNAME
        -  DATABASE_PASSWORD=$DATABASE_PASSWORD
        -  DATABASE_NAME=${DATABASE_NAME}
        -  SECRET_KEY=${SECRET_KEY}
        -  ALGORITHM=${ALGORITHM}
        -  ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}

      command: ["wait-for-it", "postgres:5432", "--", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
  

  alembic:
      build: .
      depends_on:
        - postgres
      command: ["alembic", "upgrade", "head"]

volumes:
  postgres-db: 

