name: Build and Deploy Code

on: [push,pull_request]
  # push:
  #   branches:
  #     - "main"
  #     - "dev"
  # pull_request:
  #   branches:
  #     - "dev"
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: say hi to smarti
        run: echo"Hi Smarti"